version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: cd packages/core && yarn build
            - run: cd packages/core && yarn test --coverage
workflows:
    build-and-test:
      jobs:
        - build-and-test